// This file is generated by `bun run gen:types`. Do not edit manually.
// Domain shapes (RecentCallback, LogTag, etc.) stay in types/database.ts.
//
// Placeholder until C2 is unblocked and Supabase is linked. The first successful
// `bun run gen:types` will replace this file with Supabase CLI output.

export type Database = Record<string, never>
