#!/usr/bin/env bash
# Supabase schema -> types/database.generated.ts.
#
# Usage:
#   bun run gen:types
#   SUPABASE_PROJECT_REF=xxxx bun run gen:types
#
# Prerequisite: supabase CLI installed.
#   brew install supabase/tap/supabase

set -euo pipefail

OUT="types/database.generated.ts"
PROJECT_REF="${SUPABASE_PROJECT_REF:-}"
TMP="$(mktemp)"

cleanup() {
  rm -f "$TMP"
}
trap cleanup EXIT

if ! command -v supabase >/dev/null 2>&1; then
  echo "ERROR: supabase CLI is not installed. Run: brew install supabase/tap/supabase" >&2
  exit 1
fi

if [ -n "$PROJECT_REF" ]; then
  echo "-> generating types from remote project ($PROJECT_REF)"
  supabase gen types typescript --project-id "$PROJECT_REF" > "$TMP"
else
  echo "-> generating types from local Supabase (run supabase start first)"
  supabase gen types typescript --local > "$TMP"
fi

{
  printf '%s\n' '// This file is generated by `bun run gen:types`. Do not edit manually.'
  printf '%s\n' '// Domain shapes (RecentCallback, LogTag, etc.) stay in types/database.ts.'
  printf '\n'
  cat "$TMP"
} > "$OUT"

echo "generated $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
